import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QuickViewModal } from "@/components/modules/products/QuickViewModal";
import { Header } from "@/components/shared/header/index";
import { Footer } from "@/components/shared/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* The <body> tag is essential here */}
      <body className={`${geistSans.variable} font-sans antialiased`}>
        <div className="flex flex-col min-h-screen">
      <Header />
      <main className="flex-grow">
        {children}
        <QuickViewModal/>
        </main>
      <Footer />
        </div>

      </body>
    </html>
  );
}
